### ISSUE TITLE
Can use builtin function to count bits

### ISSUE THREAD

**Issue by sh1boot** [Azuzl/parker-word-square#1]
Python (at least 3) has a built-in for counting set bits in integers: https://docs.python.org/3/library/stdtypes.html#int.bit_count

Maybe that'll help performance a little?  I don't know, this is just a drive-by comment.

https://github.com/Azuzl/parker-word-square/blob/89dcabec48b77f56f7dd47b67f59ae3b37533e13/solve.py#L156
https://github.com/Azuzl/parker-word-square/blob/89dcabec48b77f56f7dd47b67f59ae3b37533e13/solve.py#L108

**Comment by Azuzl** [comment]
Ooh, thanks! That's definitely more elegant, and it seems to speed the code up by a few percent.

I'm adding it to the repository now.
